[project]
name = "PID Controller"
version = "0.1.0"
description = "PID Controller"
authors = [{ name = "John Doe", email = "john.doe@composabl.com" }]
dependencies = [
    "composabl-core",
    "numpy",
    "scipy"
]

[composabl]
type = "skill-controller"
entrypoint = "pid.controller:Controller"
